/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_co_cyberagent_android_gpuimage_GPUImageNativeLibrary */

#ifndef _Included_jp_co_cyberagent_android_gpuimage_GPUImageNativeLibrary
#define _Included_jp_co_cyberagent_android_gpuimage_GPUImageNativeLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_co_cyberagent_android_gpuimage_GPUImageNativeLibrary
 * Method:    YUVtoRBGA
 * Signature: ([BII[I)V
 */
JNIEXPORT void JNICALL
Java_com_ybj366533_camera_library_util_GPUImageNativeLibrary_YUVtoRBGA
  (JNIEnv *, jclass, jbyteArray, jint, jint, jintArray);

/*
 * Class:     jp_co_cyberagent_android_gpuimage_GPUImageNativeLibrary
 * Method:    YUVtoARBG
 * Signature: ([BII[I)V
 */
JNIEXPORT void JNICALL
Java_com_ybj366533_camera_library_util_GPUImageNativeLibrary_YUVtoARBG
  (JNIEnv *, jclass, jbyteArray, jint, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
